#Add 'hacktoberfest' for any changes in files of the project
hacktoberfest:
- "*" 
- .github/workflows/*
- _tests_/*
- index.js
- data/*

# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'workflows' label to any change within the 'github/workflows' folder
workflows yml:
  - .github/workflows/*
  - .github/*.yml

# Add 'test' label to any change to tests files within the _tests_ folder
test:
  - _tests_/*

# Add 'source' label to any change to index.js
source:
  - index.js

#Add 'data' label to anything changed within data folder
data:
  - data/*
