name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank You for raising your first Issue! Our Team will look into the issue and discuss with you shortly!"
          pr-message: "Thank You for creating your first Pull Request! Our Team will review your code and take the necessary action, ASAP!"
